repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.13.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@7.13.0
          - "@typescript-eslint/eslint-plugin@4.7.0"
          - "@typescript-eslint/parser@4.7.0"
          - eslint-plugin-import@2.22.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        exclude: |
          (?x)(
            serverless.yml |
          )
